-- SQL Script to Create and Populate the Beneficiaries Table
-- Paste this script directly into your Supabase SQL Editor (https://supabase.com -> Project -> SQL Editor -> New Query) and click Run

-- 1. Create the beneficiaries table
create table if not exists beneficiaries (
    id bigint generated by default as identity primary key,
    name text not null,
    account_number text not null unique,
    bank_bic text,
    category text default 'Operational',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Populate beneficiaries table with the unique creditors from the transactions table
insert into beneficiaries (name, account_number, bank_bic)
select distinct on (creditor_account_number) creditor_name, creditor_account_number, creditor_party_bic
from transactions
where creditor_name is not null and creditor_account_number is not null
on conflict (account_number) do nothing;

-- 3. Disable Row Level Security (so the anon key can insert/select beneficiaries)
alter table beneficiaries disable row level security;
grant all privileges on table beneficiaries to anon, authenticated, service_role;
