-- SQL Schema for Nile University ACH Transactions Database
-- Paste this script directly into your Supabase SQL Editor (https://supabase.com -> Project -> SQL Editor -> New Query)

-- 1. Create the transactions table
create table if not exists transactions (
    id bigint generated by default as identity primary key,
    batch_id text not null,
    batch_settlement_date date,
    batch_purpose text,
    batch_currency text,
    instruction_identification text,
    end_to_end_identifier text,
    transaction_id text not null,
    transaction_amount numeric(15, 2) not null,
    debtor_name text,
    debtor_account_number text,
    debtor_party_bic text,
    creditor_name text,
    creditor_account_number text,
    creditor_party_bic text,
    transaction_purpose text,
    comment text,
    transaction_status text,
    receiving_date date,
    transaction_isostatus_reason text,
    is_printed numeric, -- Can be 0 or 1
    isostatus_description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create performance indexes for high-speed searching & sorting
create index if not exists idx_transactions_creditor_name on transactions(creditor_name);
create index if not exists idx_transactions_batch_settlement_date on transactions(batch_settlement_date desc);
create index if not exists idx_transactions_transaction_amount on transactions(transaction_amount desc);
create index if not exists idx_transactions_transaction_status on transactions(transaction_status);
create index if not exists idx_transactions_batch_id on transactions(batch_id);

-- 3. Enable RLS (optional, disable or add simple policy if using anon key)
-- For a newly created Supabase project, Row Level Security (RLS) is disabled by default on new tables
-- but if enabled, you can run the following to allow anyone to read/write using anon API keys:
alter table transactions disable row level security;

-- 4. Create custom RPC function to fetch aggregated sum and counts bypassing PostgREST's 1,000 max row limit
create or replace function get_transaction_dashboard_stats(
  search_term text default '',
  status_filter text default 'All',
  start_date text default '',
  end_date text default ''
)
returns json as $$
declare
  total_sum numeric;
  total_cnt bigint;
  accepted_cnt bigint;
  rejected_cnt bigint;
  returned_cnt bigint;
  query_filter text := '';
begin
  -- Build the filter string dynamically
  if search_term <> '' then
    query_filter := query_filter || ' and (creditor_name ilike ' || quote_literal('%' || search_term || '%') || 
                              ' or batch_id ilike ' || quote_literal('%' || search_term || '%') || 
                              ' or transaction_id ilike ' || quote_literal('%' || search_term || '%') || ')';
  end if;
  
  if status_filter <> 'All' then
    query_filter := query_filter || ' and transaction_status = ' || quote_literal(status_filter);
  end if;
  
  if start_date <> '' then
    query_filter := query_filter || ' and batch_settlement_date >= ' || quote_literal(start_date)::date;
  end if;
  
  if end_date <> '' then
    query_filter := query_filter || ' and batch_settlement_date <= ' || quote_literal(end_date)::date;
  end if;

  -- Run sum and counts
  execute 'select coalesce(sum(transaction_amount), 0), count(*) from transactions where 1=1' || query_filter 
    into total_sum, total_cnt;
    
  execute 'select count(*) from transactions where transaction_status = ''Accepted''' || query_filter 
    into accepted_cnt;
    
  execute 'select count(*) from transactions where transaction_status = ''Rejected''' || query_filter 
    into rejected_cnt;
    
  execute 'select count(*) from transactions where transaction_status = ''Returned''' || query_filter 
    into returned_cnt;

  return json_build_object(
    'totalVolume', total_sum,
    'totalCount', total_cnt,
    'acceptedCount', accepted_cnt,
    'rejectedCount', rejected_cnt,
    'returnedCount', returned_cnt
  );
end;
$$ language plpgsql security definer;

